# Generated by Django 3.1.7 on 2021-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('clas', models.TextField(blank=True)),
                ('due_date', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('done', models.TextField(blank=True)),
            ],
        ),
    ]
